# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/arr-base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="sonarr"
ARG SONARR_BRANCH="main"
ARG UPSTREAM_URL="https://services.sonarr.tv/v1/releases"
ARG DOWNLOAD_URL="https://services.sonarr.tv/v1/download/${SONARR_BRANCH}/latest?version=4&os=freebsd"
ARG UPSTREAM_JQ=".v4-stable.version"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8989/ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Sonarr" \
      org.opencontainers.image.description="Sonarr TV series management on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/sonarr" \
      org.opencontainers.image.url="https://sonarr.tv/" \
      org.opencontainers.image.documentation="https://wiki.servarr.com/sonarr" \
      org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Management" \
      io.daemonless.port="8989" \
      io.daemonless.volumes="/config,/tv,/downloads" \
      org.freebsd.jail.allow.mlock="required" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install Sonarr from FreeBSD packages
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download and install Sonarr
RUN SONARR_VERSION=$(fetch -qo - "${UPSTREAM_URL}" | grep -o '"v4-stable":{[^}]*"version":"[^"].*"' | grep -o '"version":"[^"].*' | cut -d'"' -f4) && \
    install-arr.sh "sonarr" "Sonarr" "$SONARR_VERSION" "${DOWNLOAD_URL}" "${SONARR_BRANCH}"

# Copy service definition and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/sonarr/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8989

# --- Volumes (Injected by Generator) ---
VOLUME /config /tv /downloads